version: "3"
services:
    db:
        image: postgres:latest
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
        volumes:
            - ./postgresql:/docker-entrypoint-initdb.d

    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
            - "5555:5555"
        environment:
            NODE_ENV: "production"
        depends_on:
            - db
