version: "3.8"

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydatabase
        ports:
            - "5432:5432"

    node:
        image: node:18.14.2
